// =========================================================
// ----- ME (Clerk protected)
// =========================================================

@TOKEN = eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOURwYU4xbjlTVDZ0M0pFclBhRmoxUW9IRDciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NzAyNDYwMzUsImZ2YSI6WzUsLTFdLCJpYXQiOjE3NzAyNDU5NzUsImlzcyI6Imh0dHBzOi8vY3J1Y2lhbC1jb3lvdGUtMjcuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzcwMjQ1OTY1LCJzaWQiOiJzZXNzXzM5RHp2aVlOaGNGMUJwN2FLR1pac2tKN3E0aiIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzlEeDJrVm9GRE5tb3lSVHJRT3Q2dERlZnpTIiwidiI6Mn0.DmoCLWbYLiCcABPYoKLUWLkJqWpQnJufRZAGmQp2Cx6xyeFbL0XChw0DnskO1JJ7x9x5LPA_KZLPPlGwDv3yBXqUTlkPCdmv_J5aQ0S4uuAC4jBurWY8EWCzNRG6x5WapOsuv0SOoiVd41b5R4j89nY47Y68zGIejsb1gNBw7wqXRn9zOf1LzVj561mSzhGX35_sCaeMoGUJluCBGEZv3pQm71Kce-cWgRg9bxg-UMT8TSCd1oyeMT8h4AM2nFo7jnPLylmh2uP_LkiMKiomcyewEX8AAG9vrEFg36uD_OOkR0bN0zKh7DWb7WbxCxcZB5UcIDTaTOAa59LRD6Rx3Q


###  not logged ❌
GET http://localhost:3000/api/me


### get current user (auto create in DB) ✔
GET http://localhost:3000/api/me
Authorization: Bearer {{TOKEN}}


### update home radius ✔
PATCH http://localhost:3000/api/me/home
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "homeLat": 45.5017,
  "homeLng": -73.5673,
  "homeRadiusM": 500
}


### verify profile updated ✔
GET http://localhost:3000/api/me
Authorization: Bearer {{TOKEN}}


// =========================================================
// ----- INCIDENTS -----
// =========================================================

### List incidents (limit:20) ✔
GET http://localhost:3000/api/incidents?timePeriod=jour&pdqId=30&limit=20
Accept: application/json

### GET avec Id ✔
GET http://localhost:3000/api/incidents/1


### Invalid ID (NaN) ❌
GET http://localhost:3000/api/incidents/abc

### Invalid ID (inexistant) ❌
GET http://localhost:3000/api/incidents/99999999


// =========================================================
// ----- PDQ -----
// =========================================================

### List all PDQs ✔
GET http://localhost:3000/api/pdq
Accept: application/json

### Get PDQ by ID ✔
GET http://localhost:3000/api/pdq/30
Accept: application/json



